[package]
name = "typewritingclass-compiler-native"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.8.2", features = ["napi9"] }
napi-derive = "3.5.1"
oxc_allocator = "0.112.0"
oxc_ast = "0.112.0"
oxc_parser = "0.112.0"
oxc_span = "0.112.0"
serde_json = "1.0.149"

[build-dependencies]
napi-build = "2.3.1"
